### ISSUE TITLE
 No download file in downloaded script: https://rds.ncmrwf.gov.in/

### ISSUE THREAD

**Issue by barely-sad-one** [NCMRWF/WRF_IMDAAv2#3]
When I downloaded scirpt file after the process of data.

> After running the file "wget_ncum_imdaa_20240805084708.sh" no file downloaded.

wget_ncum_imdaa_20240805084708.sh

```
#!/bin/bash

HOST=https://rds.ncmrwf.gov.in

echo 'Downloaded all files. '
echo 'Total downlaoded size is 228M.'
echo 'Bye!'
exit;
```

**Comment by vivekhazra** [comment]
Please write to Dr. Indira Rani (indirarani.s@gov.in). She is in-charge of the IMDAA data/portal and will definitely help you in this.

**Comment by Abhinesh612** [comment]
Thanks. I mailed her about this issue.

**Comment by barely-sad-one** [comment]
Thanks, I mailed her about this issue.
